### ISSUE TITLE
Fail to decorate

### ISSUE THREAD

**Issue by Aarklendoia** [fabriciocolombo/sonar-delphi#28]
Sorry, after come back to Sonar 5.1.2, I have another crash during analysing :

16:31:01.862 INFO  - Execute decorators...
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
Total time: 32.625s
Final Memory: 33M/1071M
INFO: ------------------------------------------------------------------------
ERROR: Error during Sonar runner execution
org.sonar.runner.impl.RunnerException: Unable to execute Sonar
        at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
        at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
        at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
        at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
        at org.sonar.runner.api.Runner.execute(Runner.java:100)
        at org.sonar.runner.Main.executeTask(Main.java:70)
        at org.sonar.runner.Main.execute(Main.java:59)
        at org.sonar.runner.Main.main(Main.java:53)
Caused by: org.sonar.api.utils.SonarException: Fail to decorate 'org.sonar.api.resources.File@50fd1535[key=workspace/EPE
RMIT.XE8/EPERMITCP00Tiles/sources/EPFMAIN00.pas,path=workspace/EPERMIT.XE8/EPERMITCP00Tiles/sources/EPFMAIN00.pas,filena
me=EPFMAIN00.pas,language=Delphi]'
        at org.sonar.batch.phases.DecoratorsExecutor.executeDecorator(DecoratorsExecutor.java:104)
        at org.sonar.batch.phases.DecoratorsExecutor.decorateResource(DecoratorsExecutor.java:87)
        at org.sonar.batch.phases.DecoratorsExecutor.decorateResource(DecoratorsExecutor.java:79)
        at org.sonar.batch.phases.DecoratorsExecutor.decorateResource(DecoratorsExecutor.java:79)
        at org.sonar.batch.phases.DecoratorsExecutor.execute(DecoratorsExecutor.java:71)
        at org.sonar.batch.phases.DatabaseModePhaseExecutor.execute(DatabaseModePhaseExecutor.java:127)
        at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:264)
        at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
        at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:235)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:230)
        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:220)
        at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
        at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
        at org.sonar.batch.scan.ScanTask.scan(ScanTask.java:57)
        at org.sonar.batch.scan.ScanTask.execute(ScanTask.java:45)
        at org.sonar.batch.bootstrap.TaskContainer.doAfterStart(TaskContainer.java:135)
        at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
        at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
        at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:158)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:95)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
        at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
        ... 9 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1173
        at org.sonar.batch.issue.tracking.FileHashes.getHash(FileHashes.java:89)
        at org.sonar.batch.issue.tracking.IssueTracking.setChecksumOnNewIssues(IssueTracking.java:66)
        at org.sonar.batch.issue.tracking.IssueTracking.track(IssueTracking.java:51)
        at org.sonar.batch.issue.tracking.IssueTrackingDecorator.doDecorate(IssueTrackingDecorator.java:139)
        at org.sonar.batch.issue.tracking.IssueTrackingDecorator.decorate(IssueTrackingDecorator.java:113)
        at org.sonar.batch.phases.DecoratorsExecutor.executeDecorator(DecoratorsExecutor.java:96)
        ... 36 more

**Comment by fabriciocolombo** [comment]
Are you using the same database or a new one?

**Comment by Aarklendoia** [comment]
It's a new one because the database of the 5.2 isn't compatible with the 5.1.2. I deleted all tables and sonar have created all the tables again. I can check C# porjetcs but not Delphi projects.

For information, my delphi project is a Delphi 10 Seatle project.

**Comment by fabriciocolombo** [comment]
It seems that is related to this issue: https://jira.sonarsource.com/browse/SONAR-6792

**Comment by Aarklendoia** [comment]
Ok, it's fixed in the not released version 5.1.3. I'm blocked with the two version available... I'm not Lucky!

**Comment by fabriciocolombo** [comment]
Sorry. I'm working on #16 and will finish today.

**Comment by fabriciocolombo** [comment]
Issue #16 has been fixed.
[This snapshot](https://github.com/fabriciocolombo/sonar-delphi/releases/tag/0.3.3-SNAPSHOT) can be used for Sonar 5.2 until the final version is released.
I'm closing this for now.
Feel free to reopen if you got more info about this issue.
