### ISSUE TITLE
NullPointerException excluding all delphi files

### ISSUE THREAD

**Issue by zapr-16** [fabriciocolombo/sonar-delphi#53]
I was having NullPointerException analyzing delphi files so I decided to exclude all delphi folders from the plugin configuration page. The error is still ocurring and the amount of files to parse found is the same as previous runs of sonar-runner. I've deleted ".sonar" folder from the workspace and ran it again without success.

The end of the log follows:

> 12:03:10.393 INFO  - Sensor DelphiSensor
> 12:03:10.403 INFO  - No include directories found in project configuration.
> 12:03:11.057 INFO  - Excluded: G:\TeamCity\buildAgent\work\10d8c6b1945a900a\Common
> 12:03:11.058 INFO  - Excluded: G:\TeamCity\buildAgent\work\10d8c6b1945a900a\TCH
> 12:03:11.058 INFO  - Excluded: G:\TeamCity\buildAgent\work\10d8c6b1945a900a\OrtBo
> 12:03:11.059 INFO  - Excluded: G:\TeamCity\buildAgent\work\10d8c6b1945a900a\Obsolete
> 12:03:11.059 INFO  - Excluded: G:\TeamCity\buildAgent\work\10d8c6b1945a900a\build
> 12:03:11.060 INFO  - Excluded: G:\TeamCity\buildAgent\work\10d8c6b1945a900a\Design
> 12:03:11.060 INFO  - Excluded: G:\TeamCity\buildAgent\work\10d8c6b1945a900a\ImportFiles
> 12:03:11.061 INFO  - Excluded: G:\TeamCity\buildAgent\work\10d8c6b1945a900a\NANT
> 12:03:11.062 INFO  - Parsing project Default Project
> 12:03:11.077 INFO  - Files to parse: 959
> 12:03:11.089 INFO  - 0% done...
> 12:03:11.098 INFO  - 10% done...
> 12:03:11.102 INFO  - 20% done...
> 12:03:11.105 INFO  - 30% done...
> 12:03:11.107 INFO  - 40% done...
> 12:03:11.110 INFO  - 50% done...
> 12:03:11.112 INFO  - 60% done...
> 12:03:11.119 INFO  - 70% done...
> 12:03:11.125 INFO  - 80% done...
> 12:03:11.143 INFO  - 90% done...
> INFO: ------------------------------------------------------------------------
> INFO: EXECUTION FAILURE
> INFO: ------------------------------------------------------------------------
> Total time: 5:38.917s
> Final Memory: 6M/117M
> INFO: ------------------------------------------------------------------------
> ERROR: Error during Sonar runner execution
> org.sonar.runner.impl.RunnerException: Unable to execute Sonar
>         at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
>         at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
>         at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
>         at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
>         at org.sonar.runner.api.Runner.execute(Runner.java:100)
>         at org.sonar.runner.Main.executeTask(Main.java:70)
>         at org.sonar.runner.Main.execute(Main.java:59)
>         at org.sonar.runner.Main.main(Main.java:53)
> Caused by: java.lang.NullPointerException
>         at org.sonar.plugins.delphi.DelphiSensor.parseFiles(DelphiSensor.java:200)
>         at org.sonar.plugins.delphi.DelphiSensor.analyse(DelphiSensor.java:107)
>         at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
>         at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
>         at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
>         at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:184)
>         at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
>         at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
>         at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
>         at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
>         at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
>         at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
>         at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
>         at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
>         at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
>         at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
>         at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
>         at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
>         at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:118)
>         at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:78)
>         at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:497)
>         at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
>         ... 9 more

**Comment by SandroLuck** [comment]
Try this version https://github.com/SandroLuck/SonarDelphi it fixed some Errors which occured with newer SoanrQube Vesions

**Comment by zapr-16** [comment]
Hi, SandroLuck. Thanks in advance but from what I see in your page it doesn't work with Sonar 6.0 which is the version that I'm running. I'll follow your fork for updates though

**Comment by SandroLuck** [comment]
,, "",
Am 21.10.2016 4:05 nachm. schrieb zapr-16 notifications@github.com:Hi, SandroLuck. Thanks in advance but from what I see in your page it doesn't work with Sonar 6.0 which is the version that I'm running. I'll follow your fork for updates though
